[package]
name = "rust-yespower"
version = "0.1.0"
authors = ["Yar <idquantum@gmail.com>"]
edition = "2021"
description = "Generate a yespower pow hash for Tidecoin."
license = "MIT"
readme = "README.md"
repository = "https://github.com/yarsawyer/rust-yespower"
keywords = ["yespower", "tidecoin"]

[dependencies]
libc = "0.2"
hex = "0.4.3"

[build-dependencies]
bindgen = "0.68"
cc = "1.0"
